<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-TDDV87RG" failures="1" tests="1" name="org.testing.TestScripts.TC1" time="37.032" errors="0" timestamp="2023-10-08T00:02:33 IST" skipped="0">
  <testcase classname="org.testing.TestScripts.TC1" name="tc1" time="37.032">
    <failure message="expected [https://accounts.google.com/signin/v2/challenge/iap?TL=AJeL0C4z-LUMMtCl2mlFbG3RC8L2l4yz2zAHf8c3nWS0Vg7gDWtj30Nbi8AOD2bK&amp;checkConnection=youtube%3A804%3A0&amp;checkedDomains=youtube&amp;cid=3&amp;continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Den%26next%3Dhttps%253A%252F%252Fwww.youtube.com%252F&amp;dsh=S-704166548%3A1696703390884583&amp;ec=65620&amp;flowEntry=ServiceLogin&amp;flowName=GlifWebSignIn&amp;hl=en&amp;ifkv=AYZoVheNlDIS-qdgRhGv5MrssB6jeeuzD_PrybY9A0OPjpif4h4sNTtw4pl4hSK6ZzugzoIMQsE3&amp;pstMsg=1&amp;service=youtube&amp;theme=glif] but found [https://www.youtube.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://accounts.google.com/signin/v2/challenge/iap?TL=AJeL0C4z-LUMMtCl2mlFbG3RC8L2l4yz2zAHf8c3nWS0Vg7gDWtj30Nbi8AOD2bK&checkConnection=youtube%3A804%3A0&checkedDomains=youtube&cid=3&continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Den%26next%3Dhttps%253A%252F%252Fwww.youtube.com%252F&dsh=S-704166548%3A1696703390884583&ec=65620&flowEntry=ServiceLogin&flowName=GlifWebSignIn&hl=en&ifkv=AYZoVheNlDIS-qdgRhGv5MrssB6jeeuzD_PrybY9A0OPjpif4h4sNTtw4pl4hSK6ZzugzoIMQsE3&pstMsg=1&service=youtube&theme=glif] but found [https://www.youtube.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at org.testing.TestScripts.TC1.tc1(TC1.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testing.trigger.Runner.main(Runner.java:69)
]]>
    </failure>
  </testcase> <!-- tc1 -->
  <system-out/>
</testsuite> <!-- org.testing.TestScripts.TC1 -->
